trigger:
  - none

pool:
  vmImage: 'macos-latest'

jobs:
  - job: BuildTestRelease
    displayName: Build, test and release
    steps:
      - checkout: self
        clean: true

      - task: Bash@3
        displayName: Create local.properties
        inputs:
          targetType: 'inline'
          script: |
            echo "OSSRH_USERNAME=${OSSRH_USERNAME}" >> ./local.properties
            echo "OSSRH_PASSWORD=${OSSRH_PASSWORD}" >> ./local.properties
            echo "PGP_KEY=${PGP_KEY}" >> ./local.properties
            echo "PGP_PASSWORD=${PGP_PASSWORD}" >> ./local.properties

        env:
          BINTRAY_APIKEY: $(BINTRAY_APIKEY)

      - task: Gradle@2
        displayName: Build
        inputs:
          gradleWrapperFile: 'gradlew'
          publishJUnitResults: true
          testResultsFiles: '**/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.11'
          gradleOptions: '-Xmx3072m'
          sonarQubeRunAnalysis: false
          tasks: 'assembleLibrary_androidx :library:assembleLibrary'

      - task: Gradle@2
        displayName: Publish to OSSRH
        inputs:
          gradleWrapperFile: 'gradlew'
          publishJUnitResults: true
          testResultsFiles: '**/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.11'
          gradleOptions: '-Xmx3072m'
          sonarQubeRunAnalysis: false
          tasks: 'publish'

      - task: Gradle@2
        displayName: Close OSSRH repository
        inputs:
          gradleWrapperFile: 'gradlew'
          publishJUnitResults: true
          testResultsFiles: '**/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.11'
          gradleOptions: '-Xmx3072m'
          sonarQubeRunAnalysis: false
          tasks: 'closeRepository releaseRepository'
