name: Publish to bintray on closed PR
on:
  # Trigger the workflow on push to master branch
  push:
    branches: [master]

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v1
        #Commit should be like "^Merge pull request #"
        with:
          pattern: '^Merge pull request #\d'
          flags: 'gm'
          error: 'This action runs only on PR merges. Check your commit message.'
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    # Export properties
    - name: Setup bintray credentials
      env:
        BINTRAY_APIKEY: ${{ secrets.BINTRAY_APIKEY }}
      run: |
        echo "bintray.user=queueitdevs" > ./local.properties
        echo "bintray.apiKey=${BINTRAY_APIKEY}" >> ./local.properties
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: bintrayUpload